POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "noel2@foka.fr",
  "familyName": "Foka",
  "givenName": "Noel"
}

###
POST http://localhost:3000/api/companies
Content-Type: application/json

{
  "email": "nomgnenoel@gmail.com",
  "companyName": "Google"
}

###
GET http://localhost:3000/api/companies?email=nomgnenoel@gmail.com

###
DELETE http://localhost:3000/api/companies
Content-Type: application/json

{
  "id": "cm60fjak10003viq0hcrdci08"
}

###
PATCH http://localhost:3000/api/companies
Content-Type: application/json

{
  "id" : "cm611sfzt0005viq0mh4i9wcp",
  "creatorEmail" : "nomgnenoel@gmail.com",
  "employeeEmail" : "nono@gmail.com",
  "action": "DELETE"
}