POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "noel2@foka.fr",
  "familyName": "Foka",
  "givenName": "Noel"
}

###
POST http://localhost:3000/api/companies
Content-Type: application/json

{
  "email": "nomgnenoel@gmail.com",
  "companyName": "Google"
}

###
GET http://localhost:3000/api/companies?email=nomgnenoel@gmail.com