POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "noel2@foka.fr",
  "familyName": "Foka",
  "givenName": "Noel"
}

###
POST http://localhost:3000/api/companies
Content-Type: application/json

{
  "email": "nomgnenoel@gmail.com",
  "companyName": "Google"
}

###
GET http://localhost:3000/api/companies?email=nomgnenoel@gmail.com

###
DELETE http://localhost:3000/api/companies
Content-Type: application/json

{
  "id": "cm60fjak10003viq0hcrdci08"
}

###
PATCH http://localhost:3000/api/companies
Content-Type: application/json

{
  "id" : "cm611sfzt0005viq0mh4i9wcp",
  "creatorEmail" : "nomgnenoel@gmail.com",
  "employeeEmail" : "nono@gmail.com",
  "action": "DELETE"
}

###
GET http://localhost:3000/api/employees?companyId=cm611sfzt0005viq0mh4i9wcp

###
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
  "action": "SAVE_DATA",
  "name": "Salle de réunion",
  "capacity": 100,
  "description": "Salle de réunion pour les équipes de l'entreprise",
  "companyId": "cm60fh5uf0002viq0tg3hcds9"
}

###
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
  "action": "SAVE_IMAGE",
  "imgUrl": "image.jpg",
  "roomId": "cm682gaug0000vip0up4feo1i"
}

###
GET http://localhost:3000/api/rooms?companyId=cm611wsqx0006viq0jtkf0129

###
DELETE http://localhost:3000/api/rooms
Content-Type: application/json

{
  "roomId": "cm69e9kph0004viaswai937yg"
}

###
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
  "email": "nomgnenoel@gmail.com",
  "roomId": "cm6i03ghx0000viysynfo9ccx",
  "reservationDate": "25/10/2025",
  "timeSlots": ["13:00 - 17:00", "20:00 - 24:00"]
}

###
POST http://localhost:3000/api/disponibilities
Content-Type: application/json

{
  "roomId": "cm6i03ghx0000viysynfo9ccx",
  "reservationDate": "25/10/2025"
}

###
GET http://localhost:3000/api/reservations?email=nomgnenoel@gmail.com

###
DELETE http://localhost:3000/api/reservations
Content-Type: application/json

{
  "id": "cm731aefb000bvio0r3u7sa24"
}
